//! Renders the intermediate model as Rust source: one sorted static
//! `TYPES` table, deterministic so regeneration diffs stay reviewable.

use crate::model::{ConstraintModel, ElementModel, TypeModel};

pub fn render(types: &[TypeModel], provenance: &str) -> String {
    let mut types: Vec<&TypeModel> = types.iter().collect();
    types.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    out.push_str(&format!(
        "// Generated by fhir-schema-gen from {provenance}. Do not edit.\n"
    ));
    out.push_str("use super::{Constraint, Element, Severity, TypeDef};\n\n");
    out.push_str("pub static TYPES: &[TypeDef] = &[\n");
    for t in types {
        out.push_str(&render_type(t));
    }
    out.push_str("];\n");
    out
}

fn render_type(t: &TypeModel) -> String {
    let mut elements: Vec<&ElementModel> = t.elements.iter().collect();
    elements.sort_by(|a, b| a.path.cmp(&b.path));

    let mut out = format!(
        "    TypeDef {{ name: {:?}, kind: {:?}, elements: &[\n",
        t.name, t.kind
    );
    for e in elements {
        let types: Vec<String> = e.types.iter().map(|ty| format!("{ty:?}")).collect();
        out.push_str(&format!(
            "        Element {{ path: {:?}, min: {}, max_many: {}, choice: {}, types: &[{}] }},\n",
            e.path,
            e.min,
            e.max_many,
            e.choice,
            types.join(", ")
        ));
    }
    out.push_str("    ], constraints: &[\n");
    for c in &t.constraints {
        out.push_str(&render_constraint(c));
    }
    out.push_str("    ] },\n");
    out
}

fn render_constraint(c: &ConstraintModel) -> String {
    let severity = match c.severity.as_str() {
        "error" => "Severity::Error",
        "warning" => "Severity::Warning",
        _ => "Severity::Information",
    };
    format!(
        "        Constraint {{ path: {:?}, key: {:?}, severity: {severity}, human: {:?}, expression: {:?} }},\n",
        c.path, c.key, c.human, c.expression
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_sorted_static_tables() {
        let types = vec![TypeModel {
            name: "Demo".into(),
            kind: "resource".into(),
            elements: vec![ElementModel {
                path: "name".into(),
                min: 1,
                max_many: true,
                choice: false,
                types: vec!["HumanName".into()],
            }],
            constraints: vec![],
        }];
        let out = render(&types, "test-provenance");
        assert!(out.contains("// Generated by fhir-schema-gen from test-provenance"));
        assert!(out.contains(r#"TypeDef { name: "Demo""#));
        assert!(out.contains(
            r#"Element { path: "name", min: 1, max_many: true, choice: false, types: &["HumanName"] }"#
        ));
        // deterministic: types sorted by name so diffs stay reviewable
        let twice = render(&types, "test-provenance");
        assert_eq!(out, twice);
    }
}
